// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserAuthenticator is an autogenerated mock type for the UserAuthenticator type
type UserAuthenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, _a1, password
func (_m *UserAuthenticator) Authenticate(ctx context.Context, _a1 string, password string) (string, error) {
	ret := _m.Called(ctx, _a1, password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, _a1, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, _a1, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, _a1, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserAuthenticator interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserAuthenticator creates a new instance of UserAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserAuthenticator(t mockConstructorTestingTNewUserAuthenticator) *UserAuthenticator {
	mock := &UserAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
