// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BalanceCreator is an autogenerated mock type for the BalanceCreator type
type BalanceCreator struct {
	mock.Mock
}

// CreateBalanceForUser provides a mock function with given fields: ctx, userUUID
func (_m *BalanceCreator) CreateBalanceForUser(ctx context.Context, userUUID uuid.UUID) error {
	ret := _m.Called(ctx, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBalanceCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalanceCreator creates a new instance of BalanceCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalanceCreator(t mockConstructorTestingTNewBalanceCreator) *BalanceCreator {
	mock := &BalanceCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
