basePath: /api
definitions:
  login.Request:
    properties:
      login:
        example: test@test.com
        type: string
      password:
        example: test_Password
        type: string
    required:
    - login
    - password
    type: object
  register.Request:
    properties:
      login:
        example: test@test.com
        type: string
      password:
        example: test_Password
        type: string
    required:
    - login
    - password
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: v.max
    url: http://v.max.example
  description: This is a Gophermart server.
  title: Gophermart API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: |-
        Эндпоинт используется для аутентификации пользователя.
        Логин приводится к нижнему регистру на стороне сервера
        В заголовке Authorization возвращается JWT токен для авторизации
      parameters:
      - description: Login of the user
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/login.Request'
      - description: Password of the user
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/login.Request'
      responses:
        "200":
          description: User successfully authenticated
          headers:
            Authorization:
              description: token
              type: string
        "400":
          description: Bad request
        "401":
          description: Login or password is wrong
        "500":
          description: Internal server error
      summary: Аутентификация пользователя.
  /user/register:
    post:
      consumes:
      - application/json
      description: |-
        Эндпоинт используется для регистрации нового пользователя.
        Логин приводится к нижнему регистру на стороне сервера
        В заголовке Authorization возвращается JWT токен авторизации
      parameters:
      - description: Login of the user
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/register.Request'
      - description: Password of the user
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/register.Request'
      responses:
        "200":
          description: User registered successfully
          headers:
            Authorization:
              description: token
              type: string
        "400":
          description: Bad request
        "409":
          description: User already exists
        "500":
          description: Internal server error
      summary: Регистрация нового пользователя.
swagger: "2.0"
